/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import BaseDeDatos.BaseDatos;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author berli
 */
public class VentanaAjustes extends javax.swing.JDialog {

    private static BaseDatos baseDatos = new BaseDatos();
    public static String tarifa;
    private DefaultComboBoxModel modelo = new DefaultComboBoxModel();
    String linea = "";

    /**
     * Creates new form VentanaAjustes
     */
    public VentanaAjustes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        obtenerTarifas();
        jPanel1.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        comboCargo = new javax.swing.JComboBox<>();
        txtContrasena = new javax.swing.JPasswordField();
        comboUsuarios = new javax.swing.JComboBox<>();
        comboAccion = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        btnEjecutar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etiqTarifa = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        txtTarifa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        etiqTarifaPesados = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(51, 153, 255));
        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Usuarios");

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));

        txtUsuario.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        comboCargo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facturador", "Administrador" }));

        txtContrasena.setForeground(new java.awt.Color(102, 102, 102));
        txtContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContrasenaFocusGained(evt);
            }
        });

        comboUsuarios.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        comboUsuarios.setForeground(new java.awt.Color(51, 153, 255));
        comboUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuarios" }));
        comboUsuarios.setEnabled(false);
        comboUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUsuariosActionPerformed(evt);
            }
        });

        comboAccion.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        comboAccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crear", "Editar", "Borrar" }));
        comboAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAccionActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Cancelar");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton5KeyReleased(evt);
            }
        });

        btnEjecutar.setBackground(new java.awt.Color(204, 204, 204));
        btnEjecutar.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnEjecutar.setForeground(new java.awt.Color(255, 255, 255));
        btnEjecutar.setText("Ejecutar");
        btnEjecutar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });
        btnEjecutar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnEjecutarKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 19)); // NOI18N
        jLabel5.setText("Nombre ");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 19)); // NOI18N
        jLabel6.setText("Usuario");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 19)); // NOI18N
        jLabel7.setText("Contrasena");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 19)); // NOI18N
        jLabel8.setText("Cargo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(comboAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 153, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboCargo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtContrasena, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("USUARIOS", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Tarifa Normal Actual :");

        etiqTarifa.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        etiqTarifa.setForeground(new java.awt.Color(51, 153, 255));
        etiqTarifa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqTarifa.setText("50RD$");

        btnEditar.setBackground(new java.awt.Color(204, 204, 204));
        btnEditar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        btnEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnEditarKeyReleased(evt);
            }
        });

        txtTarifa.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtTarifa.setForeground(new java.awt.Color(51, 153, 255));
        txtTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarifaActionPerformed(evt);
            }
        });
        txtTarifa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarifaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Tarifa Nueva :");

        etiqTarifaPesados.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        etiqTarifaPesados.setForeground(new java.awt.Color(51, 153, 255));
        etiqTarifaPesados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqTarifaPesados.setText("50RD$");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Tarifa Pesado Actual :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqTarifa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTarifa)
                            .addComponent(etiqTarifaPesados, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(etiqTarifa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(etiqTarifaPesados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("TARIFAS", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (!txtTarifa.getText().isEmpty()) {
            editarTarifa(txtTarifa.getText());
            obtenerTarifas();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEditarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEditarKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txtTarifa.getText().isEmpty()) {
                editarTarifa(txtTarifa.getText());
                obtenerTarifas();
            }
        }
    }//GEN-LAST:event_btnEditarKeyReleased

    private void txtTarifaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarifaKeyTyped
        metodosGenerales.formatoNumericoTextField(evt, txtTarifa, 5);
    }//GEN-LAST:event_txtTarifaKeyTyped

    private void txtTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarifaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyReleased

    }//GEN-LAST:event_jButton5KeyReleased

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        if (!(txtUsuario.getText().isEmpty() || txtNombre.getText().isEmpty() || txtContrasena.getText().isEmpty())) {

            if (comboAccion.getSelectedIndex() == 0) {
                String Linea = txtUsuario.getText() + "|" + new String(txtContrasena.getPassword()) + "|" + comboCargo.getSelectedItem().toString() + "|" + txtNombre.getText() + "|";
                baseDatos.insertarDatos(Linea, "bdUsuario.txt", null);
                borrarCampos();

            } else if (comboAccion.getSelectedIndex() == 1) {
                String lineaNueva = txtUsuario.getText() + "|" + new String(txtContrasena.getPassword()) + "|" + comboCargo.getSelectedItem().toString() + "|" + txtNombre.getText() + "|";
                baseDatos.editarArchivo("bdUsuario.txt", linea, lineaNueva);
                comboAccion.setSelectedIndex(0);
                borrarCampos();
                txtUsuario.setEnabled(true);
            } else if (comboAccion.getSelectedIndex() == 2) {
                String linea = txtUsuario.getText() + "|" + new String(txtContrasena.getPassword()) + "|" + comboCargo.getSelectedItem().toString() + "|" + txtNombre.getText() + "|";
                baseDatos.eliminarLineaDeArchivo("bdUsuario.txt", linea);
                comboAccion.setSelectedIndex(0);
                borrarCampos();
                txtUsuario.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnEjecutarActionPerformed


    private void btnEjecutarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEjecutarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEjecutarKeyReleased

    private void txtContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaFocusGained
        txtContrasena.selectAll();
    }//GEN-LAST:event_txtContrasenaFocusGained

    private void comboAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAccionActionPerformed
        if (comboAccion.getSelectedIndex() == 0) {

            comboUsuarios.setEnabled(false);
            modelo.removeAllElements();
            borrarCampos();
            habilitarCampos(true);
        } else if (comboAccion.getSelectedIndex() == 1) {

            borrarCampos();
            comboUsuarios.setEnabled(false);//es a proposito 
            modelo.removeAllElements();
            obtenerRegistrosParaCombo("bdUsuario.txt");
            comboUsuarios.setEnabled(true);//es a proposito 
            comboUsuarios.setModel(modelo);

            habilitarCampos(false);
        } else if (comboAccion.getSelectedIndex() == 2) {

            borrarCampos();
            comboUsuarios.setEnabled(false);//es a proposito 
            modelo.removeAllElements();
            obtenerRegistrosParaCombo("bdUsuario.txt");
            comboUsuarios.setEnabled(true);//es a proposito 
            comboUsuarios.setModel(modelo);
            habilitarCampos(false);

            if (comboUsuarios.getItemCount() == 1) {
                comboUsuarios.setEnabled(false);
            } else {
                comboUsuarios.setEnabled(true);
            }
        }
    }//GEN-LAST:event_comboAccionActionPerformed


    private void comboUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUsuariosActionPerformed
        if (comboAccion.getSelectedIndex() == 1) {
            accionComboUsuarios();
            habilitarCampos(true);
            txtUsuario.setEnabled(false);
        } else if (comboAccion.getSelectedIndex() == 2) {
            accionComboUsuarios();
            btnEjecutar.setEnabled(true);
        }
    }//GEN-LAST:event_comboUsuariosActionPerformed

    private void accionComboUsuarios() {
        if (comboUsuarios.isEnabled()) {
            ArrayList<String> todosUsuarios = baseDatos.obtenerTodosLosDatos("bdUsuario.txt");
            ArrayList<String> listaUsuariosEspecifico;
            String lineaObtenida = "";
            String nombre = "";
            String usuario = "";
            String contrasena = "";
            String cargo = "";

            for (int i = 0; i < todosUsuarios.size(); i++) {
                listaUsuariosEspecifico = baseDatos.obtenerDatosEnLineaEspecifica(todosUsuarios.get(i));
                usuario = listaUsuariosEspecifico.get(0);
                contrasena = listaUsuariosEspecifico.get(1);
                cargo = listaUsuariosEspecifico.get(2);
                nombre = listaUsuariosEspecifico.get(3);

                if (usuario.equals(comboUsuarios.getSelectedItem().toString())) {
                    txtNombre.setText(nombre);
                    txtUsuario.setText(usuario);
                    txtContrasena.setText(contrasena);
                    if (cargo.equalsIgnoreCase("Administrador")) {
                        comboCargo.setSelectedIndex(1);
                    }
                    linea = usuario + "|" + contrasena + "|" + cargo + "|" + nombre + "|";
                    break;
                }
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAjustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAjustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAjustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAjustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaAjustes dialog = new VentanaAjustes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JComboBox<String> comboAccion;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JComboBox<String> comboUsuarios;
    private static javax.swing.JLabel etiqTarifa;
    private static javax.swing.JLabel etiqTarifaPesados;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTarifa;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public static int obtenerTarifas() {
        String Tarifa = (String) baseDatos.obtenerDatosEnLineaEspecifica((String) baseDatos.obtenerTodosLosDatos("bdConfiguraciones.txt").get(0)).get(0);
        int tarifaInt = Integer.parseInt(Tarifa);
        tarifa = tarifaInt + "|";
        etiqTarifa.setText(tarifaInt + " RD$");
        etiqTarifaPesados.setText((tarifaInt * 2) + " RD$");
        return tarifaInt;
    }

    private void editarTarifa(String tarifaNueva) {
        baseDatos.editarArchivo("bdConfiguraciones.txt", tarifa, tarifaNueva + "|");
    }

    private void obtenerRegistrosParaCombo(String bdDeseada) {

        ArrayList<String> listaTodosLosDatos = baseDatos.obtenerTodosLosDatos(bdDeseada);
        ArrayList<String> listaDatosEspecifico;

        String nombreUsuario = "";

        for (int i = 0; i < listaTodosLosDatos.size(); i++) {

            listaDatosEspecifico = baseDatos.obtenerDatosEnLineaEspecifica(listaTodosLosDatos.get(i));

            for (int j = 0; j < listaDatosEspecifico.size(); j++) {
                if (j == 0) {
                    nombreUsuario = listaDatosEspecifico.get(j);
                    modelo.addElement(nombreUsuario);
                }
            }

        }
    }

    private void habilitarCampos(boolean estado) {
        txtUsuario.setEnabled(estado);
        txtNombre.setEnabled(estado);
        txtContrasena.setEnabled(estado);
        comboCargo.setEnabled(estado);
        btnEjecutar.setEnabled(estado);
    }

    private void borrarCampos() {
        txtNombre.setText("");
        txtContrasena.setText("");
        txtUsuario.setText("");
        comboCargo.setSelectedIndex(0);
    }
}
