/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import BaseDeDatos.BaseDatos;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author berli
 */
public class VentanaClientes extends javax.swing.JDialog {

    FileWriter Fr;
    BufferedWriter buffer;
    String nombreCarpeta = File.separator + "BD" + File.separator;
    String datosCliente;
    static ArrayList<JTextField> listaCampoDeTexto;
    BaseDatos baseDatos = new BaseDatos();
    VentanaTablas ventana;
    static boolean EditarPuedeFuncionar = false;
    private boolean estoyGuardando = true;
    private static String lineaProvinienteDeTabla = "";

    /**
     * Creates new form ventanaClientes
     */
    public VentanaClientes(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        inicializarArrayListDeCampos();
        bordesDeCampo();
        metodosGenerales.camposDeTextoMayuscula(listaCampoDeTexto);
        metodosGenerales.impedirCiertosCaracteres(listaCampoDeTexto);
        ventana = new VentanaTablas(null, true, new String[]{"NOMBRE", "CEDULA", "DIRECCION", "TELEFONO"}, "bdClientes.txt", "VentanaClientes");
        btnEditar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        etiquetaDeError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 255), null));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Cedula");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Direccion");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Telefono");

        txtNombre.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 153, 255));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtCedula.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(51, 153, 255));
        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCedulaFocusGained(evt);
            }
        });

        txtDireccion.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(51, 153, 255));

        txtTelefono.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(51, 153, 255));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        btnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnGuardarKeyReleased(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Cancelar");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton5KeyReleased(evt);
            }
        });

        etiquetaDeError.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        etiquetaDeError.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(etiquetaDeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(etiquetaDeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Registro Clientes");

        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBuscarMouseReleased(evt);
            }
        });

        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditarMouseReleased(evt);
            }
        });

        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setIcon(new ImageIcon("Imagenes/iconoClientes.png"));
        btnBuscar.setIcon(new ImageIcon("Imagenes/iconoBuscar.png"));
        btnEditar.setIcon(new ImageIcon("Imagenes/iconoEditar.png"));
        btnEliminar.setIcon(new ImageIcon("Imagenes/iconoEliminar.png"));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (estoyGuardando == true) {
            insercionDatosDeClientes();
        } else {
            edicionDeClientes();
            txtCedula.setEnabled(true);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    private void btnGuardarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (estoyGuardando == true) {
                insercionDatosDeClientes();
            } else {
                edicionDeClientes();
                txtCedula.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnGuardarKeyReleased

    private void btnBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMousePressed
        if (btnBuscar.isEnabled()) {
            btnBuscar.setBorder(BorderFactory.createEtchedBorder(Color.GRAY, null));
        }
    }//GEN-LAST:event_btnBuscarMousePressed

    private void btnBuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseReleased
        if (btnBuscar.isEnabled()) {
            btnBuscar.setBorder(null);
            accionParaBotonBuscar();
            etiquetaDeError.setText("");
            bordesDeCampo();
        }
    }//GEN-LAST:event_btnBuscarMouseReleased

    private void btnEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMousePressed
        if (EditarPuedeFuncionar) {
            if (btnEditar.isEnabled()) {
                btnEditar.setBorder(BorderFactory.createEtchedBorder(Color.GRAY, null));
            }
        }
    }//GEN-LAST:event_btnEditarMousePressed

    private void btnEditarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseReleased
        if (EditarPuedeFuncionar) {
            if (btnEditar.isEnabled()) {
                estoyGuardando = false;
                btnEditar.setBorder(null);
                habilitarCamposParaEdicion();
                txtCedula.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnEditarMouseReleased

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        metodosGenerales.formatoNumericoTextField(evt, txtTelefono, 18);
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setLookAndFeel();
        lineaProvinienteDeTabla = "";
        EditarPuedeFuncionar = false;
    }//GEN-LAST:event_formWindowClosing

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased


    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed

    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void txtCedulaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusGained
        etiquetaDeError.setText("");
    }//GEN-LAST:event_txtCedulaFocusGained

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        accionBotonCancelar();
        txtCedula.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            accionBotonCancelar();
            txtCedula.setEnabled(true);
        }
    }//GEN-LAST:event_jButton5KeyReleased

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if (focusCampoVacio() == false) {
            eliminarClientes();
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaClientes dialog = new VentanaClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEliminar;
    private static javax.swing.JButton btnGuardar;
    private javax.swing.JLabel etiquetaDeError;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    public void inicializarArrayListDeCampos() {
        listaCampoDeTexto = new ArrayList();
        listaCampoDeTexto.add(txtNombre);
        listaCampoDeTexto.add(txtCedula);
        listaCampoDeTexto.add(txtDireccion);
        listaCampoDeTexto.add(txtTelefono);
    }

    public void borrarCamposTexto() {
        for (JTextField campoActual : listaCampoDeTexto) {
            campoActual.setText(null);
        }

        bordesDeCampo();
    }

    private boolean focusCampoVacio() {
        bordesDeCampo();
        for (JTextField campoActual : listaCampoDeTexto) {

            if (campoActual.getText().trim().isEmpty()) {
                campoActual.grabFocus();
                campoActual.setBorder(BorderFactory.createEtchedBorder(Color.RED, null));

                return true;
            }
        }
        return false;
    }

    private void bordesDeCampo() {
        for (JTextField campoActual : listaCampoDeTexto) {
            campoActual.setBorder(BorderFactory.createEtchedBorder(Color.GRAY, null));
        }
    }

    public static void setLookAndFeel() {
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }

    private void insercionDatosDeClientes() {
        String lineaDeDatos = "";
        if (focusCampoVacio() == false) {
            for (JTextField campoActual : listaCampoDeTexto) {
                lineaDeDatos += campoActual.getText() + "|";
            }
            if (!validarCedulaCliente(lineaDeDatos)) {
                baseDatos.insertarDatos(lineaDeDatos, "bdClientes.txt", null);
                borrarCamposTexto();
                EditarPuedeFuncionar = false;
            }

        }
    }

    private void edicionDeClientes() {
        String lineaNueva = "";
        if (focusCampoVacio() == false) {

            for (JTextField campoActual : listaCampoDeTexto) {
                lineaNueva += campoActual.getText() + "|";
            }

            System.out.println(lineaNueva);

            baseDatos.editarArchivo("bdClientes.txt", lineaProvinienteDeTabla, lineaNueva);
            borrarCamposTexto();
            estoyGuardando = true;
            btnBuscar.setEnabled(true);
            btnEditar.setEnabled(true);
            EditarPuedeFuncionar = false;

        }

    }

    //este metodo puede ser diferente en cada clase
      public static void rellenarCamposConDatosDeTabla() {
        BaseDatos base = new BaseDatos();
        ArrayList listaLineasDeTabla = base.obtenerDatosEnLineaEspecifica(getLineaProvinienteDeTabla());
        System.out.println(getLineaProvinienteDeTabla());
        JTextField campoActual;
        String datoDeLaLineaObtenido;

        for (int i = 0; i < listaLineasDeTabla.size(); i++) {
            campoActual = listaCampoDeTexto.get(i);

            datoDeLaLineaObtenido = String.valueOf(listaLineasDeTabla.get(i));
            campoActual.setText(datoDeLaLineaObtenido);
            campoActual.setFocusable(false);

        }

        btnGuardar.setEnabled(false);
        EditarPuedeFuncionar = true;

    }

    public void habilitarCamposParaEdicion() {
        for (JTextField campoActual : listaCampoDeTexto) {
            campoActual.setFocusable(true);
        }
        btnBuscar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnGuardar.setEnabled(true);
    }

    private void accionParaBotonBuscar() {
        ventana = new VentanaTablas(null, true, new String[]{"NOMBRE", "CEDULA", "DIRECCION", "TELEFONO"}, "bdClientes.txt", "VentanaClientes");
        ventana.setVisible(true);
        //esto aqui se ve tonto , pero es la unica manera que habia para que mi jDialog sin barra de titulo saliera sin ella al invocarla.
        //la razon?? no lo se solo se que funciona. si ve esto expliqueme. perdi mucho tiempo en este errorcito.
    }

    private boolean validarCedulaCliente(String lineaActual) {

        ArrayList<String> listaTodosLosClientes = baseDatos.obtenerTodosLosDatos("bdClientes.txt");
        ArrayList<String> listaClienteEspecifico;
        ArrayList<String> lista = baseDatos.obtenerDatosEnLineaEspecifica(lineaActual);

        String cedula = lista.get(1);

        for (int i = 0; i < listaTodosLosClientes.size(); i++) {

            listaClienteEspecifico = baseDatos.obtenerDatosEnLineaEspecifica(listaTodosLosClientes.get(i));

            String cedulaObtenida = listaClienteEspecifico.get(1);

            if (cedula.equals(cedulaObtenida)) {
                etiquetaDeError.setText("DOS CLIENTES NO PUEDEN TENER LA MISMA CEDULA");
                return true;
            }
        }
        return false;
    }

    public void accionBotonCancelar() {
        borrarCamposTexto();
        EditarPuedeFuncionar = false;
        estoyGuardando = true;
        lineaProvinienteDeTabla = "";
        txtNombre.grabFocus();
        btnBuscar.setEnabled(true);
        btnEditar.setEnabled(true);
        btnGuardar.setEnabled(true);
        etiquetaDeError.setText("");

        for (JTextField campoActual : listaCampoDeTexto) {
            campoActual.setFocusable(true);
        }
    }

    public static String getLineaProvinienteDeTabla() {
        return lineaProvinienteDeTabla;
    }

    public static void setLineaProvinienteDeTabla(String aLineaProvinienteDeTabla) {
        lineaProvinienteDeTabla = aLineaProvinienteDeTabla;
    }

    private void eliminarClientes() {
        String nombre = txtNombre.getText();
        String cedula = txtCedula.getText();
        String direccion = txtDireccion.getText();
        String num = txtTelefono.getText();
        System.out.println("toy aqui");
        String linea = nombre + "|" + cedula + "|" + direccion + "|" + num + "|";

        ArrayList<String> listaVehiculos = baseDatos.obtenerTodosLosDatos("bdVehiculos.txt");
        ArrayList<String> lineaVehiculoEspecifico;

        if (listaVehiculos.size() == 0) {
            baseDatos.eliminarLineaDeArchivo("bdClientes.txt", linea);
            borrarCamposTexto();
        }

        for (int i = 0; i < listaVehiculos.size(); i++) {
            lineaVehiculoEspecifico = baseDatos.obtenerDatosEnLineaEspecifica(listaVehiculos.get(i));
            String dueno = lineaVehiculoEspecifico.get(0);

            if (dueno.equalsIgnoreCase(nombre)) {
                etiquetaDeError.setText("NO SE PUEDE ELIMINAR TIENE VEHICULOS A SU NOMBRE");
                break;
            } else {
                baseDatos.eliminarLineaDeArchivo("bdClientes.txt", linea);
                borrarCamposTexto();
                System.out.println("sigo vivooo");

            }

        }
    }

}
