/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import BaseDeDatos.BaseDatos;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.UIManager;
import FiveCodMover.FiveCodMoverJDialog;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.util.ArrayList;
import java.util.Locale;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author berli
 */
public class VentanaReportes extends javax.swing.JDialog {

    String botonSeleccionado;
    ArrayList<JTextField> listaBotones;
    DefaultTableModel modeloEstacionados = new DefaultTableModel();
    DefaultTableModel modeloRetirados = new DefaultTableModel();
    DefaultTableModel modeloVentas = new DefaultTableModel();
    BaseDatos bsd = new BaseDatos();
    String bdSeleccionada = "bdEntradas.txt";

    /**
     * Creates new form VentanaReportes
     */
    public VentanaReportes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setLookAndFeel();
        initComponents();
        cargarColumnasTablaEntrada();
        cargarColumnasTablaRetiros();
        cargarColumnasTablaVentas();
        tabla.getTableHeader().setFont(new Font("Century Gothic", Font.PLAIN, 16));
        setLocationRelativeTo(null);

        personalizacionDateChooser();

    }

    private void personalizacionDateChooser() {

        ArrayList<JDateChooser> listaDate = new ArrayList();
        listaDate.add(jDateChooser1);
        listaDate.add(jDateChooser2);

        for (JDateChooser jDateChooser : listaDate) {

            jDateChooser.setLocale(new Locale("ES"));
            jDateChooser.setDateFormatString("dd/MM/yyyy");

            jDateChooser.getCalendarButton().setContentAreaFilled(false);
            jDateChooser.getCalendarButton().setIcon(new ImageIcon("Imagenes/iconoCalendario.png"));

            JTextFieldDateEditor f = (JTextFieldDateEditor) jDateChooser.getDateEditor();

            f.setBackground(new Color(102, 102, 255));
            f.setBorder(null);
            f.setEditable(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnEstacionados = new javax.swing.JLabel();
        etiquetaTitulo = new javax.swing.JLabel();
        btnRetirados = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        btnVentas = new javax.swing.JLabel();
        etiqMonto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 204), null));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        btnEstacionados.setBackground(new java.awt.Color(42, 42, 167));
        btnEstacionados.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnEstacionados.setForeground(new java.awt.Color(255, 255, 255));
        btnEstacionados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEstacionados.setText("Estacionados");
        btnEstacionados.setOpaque(true);
        btnEstacionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstacionadosMouseClicked(evt);
            }
        });

        etiquetaTitulo.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTitulo.setText("Reportes");

        btnRetirados.setBackground(new java.awt.Color(102, 102, 255));
        btnRetirados.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnRetirados.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRetirados.setText("Retirados");
        btnRetirados.setOpaque(true);
        btnRetirados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetiradosMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Desde");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hasta");

        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(102, 102, 255));
        jDateChooser1.setForeground(new java.awt.Color(255, 153, 51));
        jDateChooser1.setDate(metodosGenerales.FechaDelDia());
        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        jDateChooser2.setBackground(new java.awt.Color(102, 102, 255));
        jDateChooser2.setForeground(new java.awt.Color(255, 153, 51));
        jDateChooser2.setDate(metodosGenerales.FechaDelDia());
        jDateChooser2.setDateFormatString("dd/MM/yyyy");
        jDateChooser2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        btnVentas.setBackground(new java.awt.Color(102, 102, 255));
        btnVentas.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVentas.setText("Venta Del Dia");
        btnVentas.setOpaque(true);
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasMouseClicked(evt);
            }
        });

        etiqMonto.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        etiqMonto.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnEstacionados, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnRetirados, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiqMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel3)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(etiquetaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEstacionados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRetirados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(etiqMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        jButton1.setIcon(new ImageIcon("Imagenes/iconoBuscar.png"));

        tabla.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tabla.setForeground(new java.awt.Color(51, 51, 51));
        tabla.setModel(modeloEstacionados);
        tabla.setToolTipText("");
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.setRowHeight(20);
        tabla.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

    }//GEN-LAST:event_tablaMouseClicked

    private void btnEstacionadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstacionadosMouseClicked
        cambiarColoresDeEtiquetas(evt);
        jDateChooser2.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setText("Hasta");
        etiqMonto.setText(null);
        tabla.setModel(modeloEstacionados);
        bdSeleccionada = "bdEntradas.txt";
        tabla.getColumnModel().getColumn(0).setPreferredWidth(150);
    }//GEN-LAST:event_btnEstacionadosMouseClicked

    private void btnRetiradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetiradosMouseClicked
        cambiarColoresDeEtiquetas(evt);
        jDateChooser2.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setText("Hasta");
        etiqMonto.setText(null);
        tabla.setModel(modeloRetirados);
        bdSeleccionada = "bdSalidas.txt";
    }//GEN-LAST:event_btnRetiradosMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        FiveCodMoverJDialog.MousePressed(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        FiveCodMoverJDialog.MouseDraggedJDialog(evt, this);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        VentanaPrincipal.setLookAndFeel();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (bdSeleccionada.equalsIgnoreCase("ventas")) {
            etiqMonto.setText(null);
            String fecha = metodosGenerales.DateAString(jDateChooser1.getDate());
            int fechaInt = Integer.parseInt(fecha.replaceAll(Pattern.quote("/"), ""));

            borrarTabla(bdSeleccionada);
            obtenerRegistosParaTablaVentas(fechaInt);

        } else {

            String fechaDesde = metodosGenerales.DateAString(jDateChooser2.getDate());
            String fechaHasta = metodosGenerales.DateAString(jDateChooser1.getDate());

            int fechaDesdeInt = Integer.parseInt(fechaDesde.replaceAll(Pattern.quote("/"), ""));
            int fechaHastaInt = Integer.parseInt(fechaHasta.replaceAll(Pattern.quote("/"), ""));

            System.out.println("" + fechaDesdeInt + "  " + fechaHastaInt);

            borrarTabla(bdSeleccionada);
            obtenerRegistrosParaLaTabla(bdSeleccionada, fechaDesdeInt, fechaHastaInt);
        }

        if (bdSeleccionada.equals("bdSalidas.txt")) {
            String valor;
            int valorint = 0;
            int numeroFilas = modeloRetirados.getRowCount();
            for (int i = 0; i < numeroFilas; i++) {
                valor = (String) modeloRetirados.getValueAt(i, 6);
                valorint = valorint + Integer.parseInt(valor);
            }
            etiqMonto.setText(valorint + " RD$");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseClicked
        cambiarColoresDeEtiquetas(evt);
        jDateChooser2.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setText("Fecha");
        etiqMonto.setText(null);
        bdSeleccionada = "ventas";
        tabla.setModel(modeloVentas);

    }//GEN-LAST:event_btnVentasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaReportes dialog = new VentanaReportes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEstacionados;
    private javax.swing.JLabel btnRetirados;
    private javax.swing.JLabel btnVentas;
    private javax.swing.JLabel etiqMonto;
    private static javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    private void setLookAndFeel() {

        try {
            for (UIManager.LookAndFeelInfo information : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(information.getName())) {
                    javax.swing.UIManager.setLookAndFeel(information.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }

    private void cambiarColoresDeEtiquetas(MouseEvent evt) {

        JLabel etiquetaSeleccionada = (JLabel) evt.getSource();
        String nombreDeBotonSeleccionada = etiquetaSeleccionada.getText();

        if (nombreDeBotonSeleccionada.equals("Estacionados")) {

            btnRetirados.setBackground(new Color(102, 102, 255));//blanco
            btnEstacionados.setBackground(new Color(42, 42, 167));//negro
            btnVentas.setBackground(new Color(102, 102, 255));

        } else if (nombreDeBotonSeleccionada.equals("Retirados")) {

            btnEstacionados.setBackground(new Color(102, 102, 255));
            btnRetirados.setBackground(new Color(42, 42, 167));
            btnVentas.setBackground(new Color(102, 102, 255));
        } else {
            btnVentas.setBackground(new Color(42, 42, 167));
            btnRetirados.setBackground(new Color(102, 102, 255));
            btnEstacionados.setBackground(new Color(102, 102, 255));
        }

        botonSeleccionado = nombreDeBotonSeleccionada;

        //De seguro usted leera esto, no pude cambiar el color del foreground del dateChooser si usted sabe como hacerlo
        //por favor envieme el codigo
    }

    private void cargarColumnasTablaVentas() {
        modeloVentas.addColumn("DUENO");
        modeloVentas.addColumn("PLACA");
        modeloVentas.addColumn("TIPO");
        modeloVentas.addColumn("DIAS");
        modeloVentas.addColumn("PAGADO");
        modeloVentas.addColumn("FECHA ENTRADA");
        modeloVentas.addColumn("FECHA SALIDA");
    }

    private void cargarColumnasTablaEntrada() {

        modeloEstacionados.addColumn("ESTACIONAMIENTO");
        modeloEstacionados.addColumn("DUENO");
        modeloEstacionados.addColumn("PLACA");
        modeloEstacionados.addColumn("MARCA");
        modeloEstacionados.addColumn("MODELO");
        modeloEstacionados.addColumn("COLOR");
        modeloEstacionados.addColumn("TIPO");
        modeloEstacionados.addColumn("FECHA");
        tabla.getColumnModel().getColumn(0).setPreferredWidth(150);
    }

    private void cargarColumnasTablaRetiros() {
        modeloRetirados.addColumn("DUENO");
        modeloRetirados.addColumn("PLACA");
        modeloRetirados.addColumn("TIPO");
        modeloRetirados.addColumn("FECHA ENTRADA");
        modeloRetirados.addColumn("FECHA SALIDA");
        modeloRetirados.addColumn("DIAS");
        modeloRetirados.addColumn("PAGADO");
    }

    private void obtenerRegistosParaTablaVentas(int fecha) {
        String bdDeseada = "bdSalidas.txt";
        ArrayList<String> listaTodosLosDatos = bsd.obtenerTodosLosDatos(bdDeseada);
        ArrayList<String> listaDatosEspecifico;

        int montoInt = 0;
        String dueno = "";
        String placa = "";
        String tipo = "";
        String fecha2 = "";
        String fechaEntrada = "";
        String monto = "";

        for (int i = 0; i < listaTodosLosDatos.size(); i++) {

            listaDatosEspecifico = bsd.obtenerDatosEnLineaEspecifica(listaTodosLosDatos.get(i));

            dueno = listaDatosEspecifico.get(0);
            placa = listaDatosEspecifico.get(1);
            fechaEntrada = listaDatosEspecifico.get(2);
            fecha2 = listaDatosEspecifico.get(3);
            monto = listaDatosEspecifico.get(4);
            tipo = listaDatosEspecifico.get(5);

            int fechaInt = Integer.parseInt(fecha2.replaceAll(Pattern.quote("/"), ""));
            System.out.println("" + fechaInt);

            if (fechaInt == fecha) {

                long Dias = metodosGenerales.DiasEntreFecha(fechaEntrada, fecha2);

                montoInt = montoInt + Integer.parseInt(monto);
                if (Dias == 0) {
                    Dias = 1;
                }
                String[] datos = {dueno, placa, tipo, new String("" + Dias), monto, fechaEntrada, fecha2};
                modeloVentas.addRow(datos);
                etiqMonto.setText(montoInt + " RD$");

            }
        }
    }

    private void obtenerRegistrosParaLaTabla(String bdDeseada, int fechaDesde, int fechaHasta) {

        ArrayList<String> listaTodosLosDatos = bsd.obtenerTodosLosDatos(bdDeseada);
        ArrayList<String> listaDatosEspecifico;

        String dueno = "";
        String placa = "";
        String marca = "";
        String modelo = "";
        String color = "";
        String tipo = "";
        String fecha = "";
        String fechaEntrada = "";
        String monto = "";
        String estacionamiento = "";

        for (int i = 0; i < listaTodosLosDatos.size(); i++) {

            listaDatosEspecifico = bsd.obtenerDatosEnLineaEspecifica(listaTodosLosDatos.get(i));

            if (bdDeseada.equals("bdEntradas.txt")) {

                estacionamiento = listaDatosEspecifico.get(0);
                dueno = listaDatosEspecifico.get(1);
                placa = listaDatosEspecifico.get(2);
                marca = listaDatosEspecifico.get(3);
                modelo = listaDatosEspecifico.get(4);
                color = listaDatosEspecifico.get(5);
                tipo = listaDatosEspecifico.get(6);
                fecha = listaDatosEspecifico.get(7);
            } else if (bdDeseada.equals("bdSalidas.txt")) {

                dueno = listaDatosEspecifico.get(0);
                placa = listaDatosEspecifico.get(1);
                fechaEntrada = listaDatosEspecifico.get(2);
                fecha = listaDatosEspecifico.get(3);
                monto = listaDatosEspecifico.get(4);
                tipo = listaDatosEspecifico.get(5);
            }

            int fechaInt = Integer.parseInt(fecha.replaceAll(Pattern.quote("/"), ""));
            System.out.println("" + fechaInt);

            if (fechaInt >= fechaDesde && fechaInt <= fechaHasta) {

                if (bdDeseada.equals("bdEntradas.txt")) {

                    String[] datos = {estacionamiento, dueno, placa, marca, modelo, color, tipo, fecha};
                    modeloEstacionados.addRow(datos);
                } else if (bdDeseada.equals("bdSalidas.txt")) {
                    long Dias = metodosGenerales.DiasEntreFecha(fechaEntrada, fecha);
                    if (Dias == 0) {
                        Dias = 1;
                    }
                    String[] datos = {dueno, placa, tipo, fechaEntrada, fecha, new String("" + Dias), monto};
                    modeloRetirados.addRow(datos);
                }
            }
        }
    }

    private void borrarTabla(String bd) {

        if (bd.equals("bdEntradas.txt")) {

            int numeroDeFilas = modeloEstacionados.getRowCount();

            for (int i = numeroDeFilas - 1; i >= 0; i--) {
                modeloEstacionados.removeRow(i);
            }

        } else if (bd.equals("bdSalidas.txt")) {

            int numeroDeFilas2 = modeloRetirados.getRowCount();

            for (int i = numeroDeFilas2 - 1; i >= 0; i--) {
                modeloRetirados.removeRow(i);
            }

        } else {

            int numeroDeFilas3 = modeloVentas.getRowCount();

            for (int i = numeroDeFilas3 - 1; i >= 0; i--) {
                modeloVentas.removeRow(i);
            }
        }
    }
}
